### ISSUE TITLE
his name is Pythagoras, package should be Pythagoras.jl

### ISSUE THREAD

**Issue by JeffreySarnoff** [freemin7/Pythagorus#1]

**Comment by JeffreySarnoff** [comment]
and the initial source file is `src/Pythagoras.jl` matching the full pkg name
(this is standard practice for Julia packages, although it is not a requirement -- it works better)

**Comment by freemin7** [comment]
Thank you for the valuable insight. I am not sure i will turn it into a standalone package so i was not sure if picking .jl was appropriate.
I am aware of my miss spelling however i see no problem with this choice of a packet name, since Pythagoras.jl would be more fitting for some geometry package.
I consider adding .jl

**Comment by JeffreySarnoff** [comment]
quite reasonable

**Comment by freemin7** [comment]
How would i go about renaming it?

**Comment by JeffreySarnoff** [comment]
You do not have many files here.  Just create a new repository with the name you choose.
Open a file and click `raw`, copy that and create the same file in the new repository, paste and save.
(It is not necessary to click `raw` before copying)

**Comment by JeffreySarnoff** [comment]
then delete the old repo
